import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const distDir = "dist";

function ensureDist() {
	fs.mkdirSync(distDir, { recursive: true });
}

function copyManifest() {
	ensureDist();
	fs.copyFileSync("manifest.json", path.join(distDir, "manifest.json"));
}

function copyPythonHelper() {
	ensureDist();
	const target = path.join(distDir, "python");
	fs.rmSync(target, { recursive: true, force: true });
	fs.cpSync("python", target, { recursive: true });
}

function copyStaticAssets() {
	copyManifest();
	copyPythonHelper();
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(distDir, "main.js"),
	minify: prod,
});

function buildStyles() {
	ensureDist();
	const xtermCss = fs.readFileSync(
		path.resolve("node_modules/@xterm/xterm/css/xterm.css"),
		"utf8"
	);
	const pluginCss = fs.readFileSync("src/plugin.css", "utf8");
	fs.writeFileSync(path.join(distDir, "styles.css"), xtermCss + "\n" + pluginCss);
}

buildStyles();
copyStaticAssets();

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	fs.watchFile("src/plugin.css", { interval: 300 }, () => {
		buildStyles();
		console.log("[css] dist/styles.css rebuilt");
	});
	fs.watchFile("manifest.json", { interval: 300 }, () => {
		copyManifest();
		console.log("[manifest] dist/manifest.json rebuilt");
	});
}
