import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"node-pty",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

function buildStyles() {
	const xtermCss = fs.readFileSync(
		path.resolve("node_modules/@xterm/xterm/css/xterm.css"),
		"utf8"
	);
	const pluginCss = fs.readFileSync("src/plugin.css", "utf8");
	fs.writeFileSync("styles.css", xtermCss + "\n" + pluginCss);
}

buildStyles();

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	fs.watchFile("src/plugin.css", { interval: 300 }, () => {
		buildStyles();
		console.log("[css] styles.css rebuilt");
	});
}
